# Generated by Django 2.1.3 on 2019-10-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20191010_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='lng',
        ),
    ]
