# Generated by Django 2.1.3 on 2019-10-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20191011_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
