# Generated by Django 2.1.3 on 2019-10-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20191011_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='pic',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
