# Generated by Django 2.1.3 on 2019-10-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20191011_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='user',
        ),
    ]
