# Generated by Django 2.2 on 2019-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_postdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='purpose',
            field=models.CharField(choices=[('0', 'テストだよ'), ('1', 'テスト２号だよ')], max_length=10),
        ),
    ]
