# Generated by Django 2.2.3 on 2019-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20191011_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='purpose',
            field=models.CharField(max_length=16),
        ),
    ]
