# Generated by Django 2.2.3 on 2019-10-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20191012_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='posted_at',
            new_name='post_time',
        ),
    ]
