# Generated by Django 2.1.3 on 2019-10-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20191012_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='post_flag',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
